name = "LaguerreVoronoi"
uuid = "e2403620-b030-4fa5-8994-0cb25fd74009"
authors = ["Claudio Contardo <ccontard@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QHull = "a8468747-bd6f-53ef-9e5c-744dbc5c59e7"

[compat]
QHull = "0.1.2"
julia = "1.3"
